filestat 코드 작성
developerTae/Project2 pull request #8
Opened 2021-04-27 13:39 UTC by developerTae

확인부탁드립니닷

2021-04-27 13:39 UTC, hydenny commented
확인했습니다

2021-04-27 13:39 UTC, YuHyeonGeun-KOR commented
확인했습니다

2021-04-27 13:40 UTC, Akgop commented
확인했습니다.

2021-04-27 13:44 UTC, YuHyeonGeun-KOR commented on main.c
> +    stat("text2", &stat2);
이상 없이 잘 구현되었습니다 수고하셨습니다.

2021-04-27 13:44 UTC, Akgop requested changes
더 짧게 수정해주세요

2021-04-27 13:44 UTC, Akgop commented on main.c
>  }
함수가 void 형이라 return문 없어도 될 것 같습니다.

2021-05-04 01:22 UTC, developerTae commented on main.c
>  }
네 수정하겠습니다!

2021-05-04 01:28 UTC, closed without merging

2021-05-04 03:01 UTC, hydenny reviewed
확인했습니다~